### ISSUE TITLE
yarn 报错 

### ISSUE THREAD

**Issue by VanquisherMe** [Weibozzz/next-blog#1]
![7785e5ef-856e-4bde-8e00-74a0c0d05c60](https://user-images.githubusercontent.com/4927398/45596868-a4559b80-b9f5-11e8-997c-5a1bd69a6919.png)
最近也在研究这个
看了一下你这里启动了 css module？
是如何吧antd 的样式排除在外的？

**Comment by Weibozzz** [comment]
可以看 #2

**Comment by Weibozzz** [comment]
yarn 报错  可以试试cnpm 现在运行不起来吗  我这边克隆 并没有问题
