### ISSUE TITLE
关于启动报错和mysql

### ISSUE THREAD

**Issue by hlipeter** [Weibozzz/next-blog#10]
yarn 加载依赖失败！
```
[2/4] 🚚  Fetching packages...
error hawk@0.10.2: The engine "node" is incompatible with this module. Expected version "0.8.x". Got "12.10.0"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```
明显依赖版本未跟进导致，俺也懒得修了。。。

进来是想看，next js 怎么和mysql 在同一服务端口下结合运用的，结果发现你这根本就没有 mysql ，你搭了个 mysql 进来有什么意义？造成网络数据污染，好气噢.......

建议删掉 不存在的、与当前项目依赖无关的标签......

如果有mysql搭载的方法，请告知！

for example next.js + mongodb :

https://thecodebarbarian.com/building-a-nextjs-app-with-mongodb

**Comment by Weibozzz** [comment]
mysql是本博客的后端服务，在这里没有开放后端代码，望理解
