### ISSUE TITLE
Nextjs 集成Antd

### ISSUE THREAD

**Issue by VanquisherMe** [Weibozzz/next-blog#2]
我的例子 https://github.com/VanquisherMe/with-nextjs-antd-app
我期望达到
1 能按需加载less 
2 能够使用 less 引入， 可以覆盖主题变量
3 开启 css module :true ,antd 以正常的模式 引入

**Comment by Weibozzz** [comment]
1和3按需加载配置，css module
按需加载就是这个  libraryName。
开启 css module :true 暂时写在页面里面。
其他具体可以看官方文档 [https://github.com/zeit/next.js#automatic-code-splitting](https://github.com/zeit/next.js#automatic-code-splitting)
.babelrc文件
```
{
  "presets": ["next/babel"],
  "plugins": [
    "transform-decorators-legacy",
    [
      "import",
      {
        "libraryName": "antd",
        "style": "less"
      }
    ]
  ]
}
```
next.config.js文件配置

2.主题配置
antd-custom.less
